version: '3.8'

services:

  db:
    image: postgres:13
    container_name: nextapp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nextapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8088:8080"
    networks:
      - nextapp_network

volumes:
  db_data:

networks:
  nextapp_network:
    driver: bridge
